name: finance_tracker_mobile
description: Offline-first personal finance tracker.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.7.0
  get_it: ^7.7.0
  injectable: ^2.4.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  fl_chart: ^0.69.0
  intl: ^0.19.0
  uuid: ^4.5.1
  workmanager: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.4.2
  build_runner: ^2.4.12
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
